on: [push]

jobs:
  stm32_ci_job:
    runs-on: ubuntu-latest
    name: A job to run CI for stm32
    steps:
    - uses: actions/checkout@v2
    - name: My CI action step
      id: stm32ci
      uses: milesfrain/stm32-action@v0.4

